version: 2

jobs:
  build:
    docker:
      - image: cimg/node:16.14.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restoring dependencies
          keys:
            - node-modules-v1-{{ checksum "yarn.lock" }}
            - node-modules-v1-
            - node-modules-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node-modules-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Build
          command: yarn build

      - run:
          name: Copy build files
          command: | 
            cp -r build ~/build
            cp -r .git ~/build/.git
            cd ~/build
            git checkout -b pages || git checkout pages
            git push --force --set-upstream origin pages