version: 2

jobs:
  build:
    docker:
      - image: cimg/node:16.14.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Build
          command: yarn build

      - run:
          name: Copy build files
          command: | 
            cp -r build ~/build
            cp -r .git ~/build/.git
            cd ~/build
            git checkout -b pages || git checkout pages
            git push --force --set-upstream origin pages